import sys
import os

# Set testing guardrail environment variable
os.environ["INTEGRATION_TESTING"] = "true"

import json
import sqlite3

# Set system path to workspace root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Force stdout to UTF-8 to prevent Windows console encoding issues
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass


from backend.app.security.auth_handler import auth_handler
from agents.orchestrator import MasterOrchestrator

DB_PATH = "careerforge.db"

def verify_integration():
    print("--- STARTING END-TO-END SYSTEM INTEGRATION TEST ---")
    
    # 1. Verify Database Connection
    if not os.path.exists(DB_PATH):
        print(f"Error: Database file '{DB_PATH}' not found. Run bootstrap script first.")
        sys.exit(1)
        
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    
    # Check seeded databases
    cur.execute("SELECT COUNT(*) FROM skills")
    skills_count = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM courses")
    courses_count = cur.fetchone()[0]
    print(f"✓ SQLite Connected. Seeded skills: {skills_count}, Seeded courses: {courses_count}")
    
    # 2. Setup Mock User
    mock_email = "test_student@careerforge.ai"
    mock_password = "SecurePassword123"
    
    # Delete if exists
    cur.execute("DELETE FROM users WHERE email = ?", (mock_email,))
    conn.commit()
    
    # Register Mock User
    user_id = "test-user-uuid-1234"
    hashed_pwd = auth_handler.hash_password(mock_password)
    cur.execute(
        "INSERT INTO users (id, email, password_hash) VALUES (?, ?, ?)",
        (user_id, mock_email, hashed_pwd)
    )
    conn.commit()
    print("✓ Registered mock test user in database.")
    
    # Verify Authentication
    cur.execute("SELECT password_hash FROM users WHERE email = ?", (mock_email,))
    saved_hash = cur.fetchone()[0]
    auth_ok = auth_handler.verify_password(mock_password, saved_hash)
    assert auth_ok, "Authentication verification failed!"
    print("✓ User password hashing and verification verified.")
    
    # Generate Token
    token = auth_handler.create_access_token(user_id, mock_email)
    decoded = auth_handler.decode_access_token(token)
    assert decoded["sub"] == user_id, "JWT sub mapping mismatch!"
    print("✓ JWT creation and validation verified.")
    
    # 3. Trigger Master Orchestrator Onboarding Flow (Multi-Agent Pipeline)
    orchestrator = MasterOrchestrator()
    allowed_slots = [
        {"day": "Monday", "start": "18:00", "end": "20:00"},
        {"day": "Saturday", "start": "09:00", "end": "14:00"}
    ]
    
    print("\n[Executing Multi-Agent Orchestrator Pipeline...]")
    # Run the orchestrator onboarding (triggers Planner, Task Optimizer, Study Coach, and Scheduler agents)
    result = orchestrator.run_onboarding_pipeline(
        user_id=user_id,
        resume_path=None,
        target_role="Machine Learning Engineer",
        timeline_months=6,
        allowed_slots=allowed_slots
    )
    
    assert result["status"] == "pending_approval", "Orchestration pipeline should pause at pending approval!"
    assert result["approval_id"] is not None, "Approval ID not generated!"
    
    # Simulate User Approving the proposed schedule
    print("[Test Integration] Simulating user-in-the-loop schedule approval...")
    final_result = orchestrator.complete_onboarding_pipeline(
        user_id=user_id,
        approval_id=result["approval_id"]
    )
    
    # Merge final approved outputs into result for downstream assertions
    result = {**result, **final_result}
    result["status"] = "success"

    # 4. Assertions on Orchestrator outputs
    print("\nAsserting Pipeline outputs...")
    assert result["status"] == "success", "Orchestration pipeline failed!"
    assert result["roadmap_id"] is not None, "Roadmap ID not generated!"

    
    roadmap = result["roadmap"]
    print(f"✓ Career Roadmap pivot to: {roadmap['target_role']}")
    print(f"✓ Timeline duration set to: {roadmap['duration_months']} months")
    
    milestones = roadmap["milestones"]
    assert len(milestones) > 0, "No milestones generated by Planner agent!"
    print(f"✓ Planner Agent generated {len(milestones)} milestones:")
    for m in milestones:
        print(f"  - {m['title']} (Courses: {', '.join(m.get('recommended_courses', []))})")
        
    schedules = result["scheduled_sessions"]
    assert len(schedules) > 0, "No calendar bookings generated by Scheduler agent!"
    print(f"✓ Scheduler Agent booked {len(schedules)} slots on user's calendar:")
    for s in schedules[:3]:
        print(f"  - [{s['title']}] starts: {s['start']} | ends: {s['end']}")
    if len(schedules) > 3:
        print(f"  - ... and {len(schedules)-3} more sessions.")
        
    quiz = result["diagnostic_quiz"]
    assert len(quiz) > 0, "No diagnostic quiz generated by Study Coach agent!"
    print(f"✓ Exam / Study Coach generated {len(quiz)} questions for first milestone:")
    for q in quiz:
        print(f"  - Question: {q['text']}")
        
    notes = result["first_milestone_notes"]
    assert len(notes) > 0, "No study notes generated by Study Coach agent!"
    print(f"✓ Exam / Study Coach generated study guide preview:\n---\n{notes[:250]}...\n---")

    # 5. Check Persistence and Security Auditing
    print("\nValidating Data Persistence & Audit trail...")
    
    # Check roadmaps
    cur.execute("SELECT id FROM roadmaps WHERE user_id = ?", (user_id,))
    db_roadmap = cur.fetchone()
    assert db_roadmap is not None, "Roadmap record missing in database!"
    
    # Check audit logs
    cur.execute("SELECT action, target_agent, correlation_id FROM audit_logs WHERE user_id = ?", (user_id,))
    logs = cur.fetchall()
    assert len(logs) > 0, "Audit logs missing in database!"
    print(f"✓ Security Gateway recorded {len(logs)} audit transactions:")
    for log in logs:
        print(f"  - Action: {log[0]} | Triggered Agent: {log[1]} | Correlation ID: {log[2][:8]}...")

    conn.close()
    print("\n--- ALL END-TO-END SYSTEM INTEGRATION TESTS PASSED SUCCESSFULY ---")

if __name__ == "__main__":
    verify_integration()
